settings:
  network:
      port: 3005
  database:
      uri: "postgresql://postgres:openshield@postgres:5432/postgres"
      auto_migration: true
  redis:
      uri: "redis://redis:6379/0"
      ssl: false
  cache:
      enabled: true
      ttl: 3600
  rate_limiting:
      enabled: true
      max: 100
      window: 60
  audit_logging:
      enabled: true
  usage_logging:
      enabled: true
  rule_server:
       url: "http://ruleserver:8000"
  rag_server:
        url: "http://ragserver:8001"
        chunking:
          size: 100
          overlap: 10

providers:
  openai:
    enabled: true
  huggingface:
    enabled: true


rules:
  input:
    - name: "prompt_injection_example"
      type: "prompt_injection"
      enabled: true
      config:
        plugin_name: "prompt_injection_llm"
        threshold: 0.85
      action:
        type: "block"