settings:
  network:
      port: 3005
  database:
      uri: "postgres://postgres:openshield@postgres:5432/postgres"
      auto_migration: true
  redis:
      uri: "redis://redis:6379/0"
      ssl: false
  cache:
      enabled: true
      ttl: 3600
  context_cache:
    enabled: true
    url: "http://cache:8080"
  rate_limiting:
      enabled: true
      max: 100
      window: 60
  audit_logging:
      enabled: true
  usage_logging:
      enabled: true
  rule_server:
       url: "http://rule:8000"

providers:
  openai:
    enabled: true
    base_url: "https://api.openai.com/v1"
  huggingface:
    enabled: true


rules:
  input:
    - name: "VigillLM"
      type: "vigilllm"
      enabled: true
      order_number: 2
      config:
        plugin_name: "vigilllm"
        threshold: 0.7
        relation: ">"
      action:
        type: "block"
