version: "3"
services:
  db:
    hostname: 127.0.0.1
    image: pgvector/pgvector:pg16
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_DB=vectordb
      - POSTGRES_USER=vectoruser
      - POSTGRES_PASSWORD=vectorpass123
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql